# Generated by Django 5.2.4 on 2025-09-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_downloademail_delete_downloadrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloademail',
            name='downloaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
