# Generated by Django 5.2.4 on 2025-09-09 07:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_downloademail_downloaded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('company', models.CharField(blank=True, max_length=150, null=True, verbose_name='Company Name')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('product', models.CharField(blank=True, choices=[('', 'Select a product'), ('acetic-acid', 'Acetic Acid'), ('sodium-hydroxide', 'Sodium Hydroxide'), ('sulfuric-acid', 'Sulfuric Acid'), ('hydrochloric-acid', 'Hydrochloric Acid'), ('other', 'Other')], max_length=50, null=True, verbose_name='Product Interest')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
