# Generated by Django 5.2.4 on 2025-11-05 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(help_text='Bootstrap icon class name', max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.AlterField(
            model_name='contact',
            name='product',
            field=models.CharField(blank=True, choices=[('', 'Select a product'), ('MEA TRIAZINE 78%', 'MEA TRIAZINE 78%'), ('P-TOLUENE SULPHONIC ACID', 'P-TOLUENE SULPHONIC ACID'), ('DIISOPROPYLAMINO ETHYLYNE DIAMINE', 'DIISOPROPYLAMINO ETHYLYNE DIAMINE'), ('SODIUM CUMENE SULPHONATE', 'SODIUM CUMENE SULPHONATE'), ('other', 'Other')], max_length=50, null=True, verbose_name='Product Interest'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.TextField()),
                ('icon_text', models.CharField(help_text='Short text shown in product icon', max_length=10)),
                ('purity', models.CharField(blank=True, max_length=50)),
                ('packaging', models.CharField(blank=True, max_length=100)),
                ('application', models.CharField(blank=True, max_length=100)),
                ('grade', models.CharField(blank=True, max_length=100)),
                ('form', models.CharField(blank=True, max_length=100)),
                ('cas_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.productcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
