# Generated by Django 5.2.4 on 2025-11-05 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_productcategory_alter_contact_product_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='description',
        ),
    ]
