# Generated by Django 5.2.4 on 2025-11-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_productcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_Category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
