# Generated by Django 5.2.4 on 2025-11-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-priority', 'name']},
        ),
        migrations.AddField(
            model_name='product',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher number = higher priority (will appear first)'),
        ),
    ]
