# Generated by Django 5.2.4 on 2025-11-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_product_options_product_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended size: 354x200 pixels', null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='icon_text',
            field=models.CharField(blank=True, help_text='Short text shown if no image is uploaded', max_length=10),
        ),
    ]
