# Generated by Django 5.2.4 on 2025-11-06 07:59

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_product_image_alter_product_icon_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Product_Category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='icon_text',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='product',
            name='coa_pdf',
            field=models.FileField(blank=True, help_text='Certificate of Analysis (PDF)', null=True, storage=app.models.get_file_storage, upload_to='product_coa/'),
        ),
        migrations.AddField(
            model_name='product',
            name='tds_pdf',
            field=models.FileField(blank=True, help_text='Technical Data Sheet (PDF)', null=True, storage=app.models.get_file_storage, upload_to='product_tds/'),
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, help_text='Product demonstration video', null=True, storage=app.models.get_file_storage, upload_to='product_videos/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='application',
            field=models.CharField(blank=True, help_text='Primary applications', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cas_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CAS Number'),
        ),
        migrations.AlterField(
            model_name='product',
            name='form',
            field=models.CharField(blank=True, help_text='Physical form (e.g., Liquid, Powder)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='grade',
            field=models.CharField(blank=True, help_text='Product grade (e.g., Industrial, Pharma)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Product image (354x200 pixels recommended)', null=True, storage=app.models.get_file_storage, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='packaging',
            field=models.CharField(blank=True, help_text='Packaging details (e.g., 200kg Drum)', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='purity',
            field=models.CharField(blank=True, help_text='Purity percentage or description', max_length=150, null=True),
        ),
    ]
