# Generated by Django 5.2.4 on 2025-11-06 08:36

import devapp.settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_product_image_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='application',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='coa_pdf',
            field=models.FileField(blank=True, help_text='Certificate of Analysis (PDF)', null=True, storage=devapp.settings.get_file_storage_instance, upload_to='product_coa/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='form',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='grade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Google Drive direct image URL (use format: https://drive.google.com/uc?export=view&id=FILE_ID)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='packaging',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher number = higher priority'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purity',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tds_pdf',
            field=models.FileField(blank=True, help_text='Technical Data Sheet (PDF)', null=True, storage=devapp.settings.get_file_storage_instance, upload_to='product_tds/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, help_text='Product demonstration video', null=True, storage=devapp.settings.get_file_storage_instance, upload_to='product_videos/'),
        ),
    ]
