# Generated by Django 5.2.4 on 2025-11-06 11:36

import app.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_product_application_alter_product_coa_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='appearance',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='assay',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='boiling_point',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='density',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='detailed_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='formula',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='gallery_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='gallery_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='iso_certifications',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='melting_point',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='molecular_weight',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='application',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cas_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='coa_pdf',
            field=models.FileField(blank=True, help_text='Certificate of Analysis (PDF)', null=True, storage=app.models.get_file_storage, upload_to='product_coa/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Google Drive direct image URL (format: https://drive.google.com/uc?export=view&id=FILE_ID)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tds_pdf',
            field=models.FileField(blank=True, help_text='Technical Data Sheet (PDF)', null=True, storage=app.models.get_file_storage, upload_to='product_tds/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, help_text='Product demonstration video', null=True, storage=app.models.get_file_storage, upload_to='product_videos/'),
        ),
        migrations.CreateModel(
            name='ProductApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='app.product')),
            ],
        ),
    ]
