# Generated by Django 5.2.4 on 2025-11-07 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_product_appearance_product_assay_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('sales_phone', models.CharField(max_length=50)),
                ('sales_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp_number', models.URLField(blank=True, max_length=50, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Company Information',
                'verbose_name_plural': 'Company Information',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='https://lh3.googleusercontent.com/d/ID)', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='CompanyFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField(blank=True)),
                ('CompanyInformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='app.companyinformation')),
            ],
        ),
    ]
