# Generated by Django 5.2.4 on 2025-11-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_companyblog_productblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='base_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
