# Generated by Django 5.2.4 on 2025-11-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_companyinformation_base_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyblog',
            name='meta_description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='companyblog',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='companyblog',
            name='meta_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='companyinformation',
            name='meta_description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='companyinformation',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='companyinformation',
            name='meta_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='schema_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating for schema.org (0.00 - 5.00)', max_digits=3),
        ),
        migrations.AddField(
            model_name='product',
            name='schema_review_count',
            field=models.IntegerField(default=0, help_text='Number of reviews for schema.org'),
        ),
        migrations.AddField(
            model_name='productblog',
            name='meta_description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='productblog',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='productblog',
            name='meta_title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
