# Generated by Django 5.2.4 on 2025-11-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_companyblog_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyblog',
            name='meta_description',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='companyblog',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=1300),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='meta_description',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=1300),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=1300),
        ),
        migrations.AlterField(
            model_name='productblog',
            name='meta_description',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='productblog',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=1300),
        ),
    ]
