# Generated by Django 5.2.4 on 2025-12-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_companyblog_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyblog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
